import Head from "next/head";
import type { NextPage } from "next";
import { Box, Container } from "@chakra-ui/react";
import { motion } from "framer-motion";
import { AboutSection, BannerSection, ContactSection, Footer, Navbar, ShowcaseSection } from "../components";
import ContainerBreakpoints from "../styles/container-breakpoints";
import { ReactElement } from "react";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Rashite Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<TransitionWrapper initialY={-20}>
				<Navbar />
			</TransitionWrapper>

			<Box as="main" bg="transparent url('/assets/bg-svg.svg') no-repeat center" bgSize="cover">
				<Container {...ContainerBreakpoints}>
					{[
						<BannerSection key={1} />,
						<ShowcaseSection key={2} />,
						<AboutSection key={3} />,
						<ContactSection key={4} />,
					]?.map((section, i) => (
						<TransitionWrapper key={i}>{section}</TransitionWrapper>
					))}
				</Container>
			</Box>

			<Footer />
		</>
	);
};

const TransitionWrapper = ({ children, initialY = 100 }: { children: ReactElement; initialY?: number }) => (
	<motion.div
		initial={{ opacity: 0, y: initialY }}
		whileInView={{ opacity: 1, y: 0 }}
		transition={{ delay: 0.1, y: { duration: 0.5 } }}
		viewport={{ once: true }}
	>
		{children}
	</motion.div>
);

export default Home;
