import Head from "next/head";
import type { NextPage } from "next";
import { Box, Container } from "@chakra-ui/react";
import {
  AboutSection,
  BannerSection,
  ContactSection,
  Footer,
  Navbar,
  ShowcaseSection,
} from "../components";
import ContainerBreakpoints from "../styles/container-breakpoints";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rashite Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Box
        as="main"
        bg="transparent url('/assets/bg-svg.svg') no-repeat center"
      >
        <Container {...ContainerBreakpoints}>
          <BannerSection />
          <ShowcaseSection />
          <AboutSection />
          <ContactSection />
        </Container>
      </Box>

      <Footer />
    </>
  );
};

export default Home;
