/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import NextLink from "next/link";
import Image from "next/image";
import { motion } from "framer-motion";
import { Box, Flex, Heading, Text } from "@chakra-ui/react";
import { RightArrow } from "../components/svg-assets";

const Branding: NextPage = () => {
	const ImgWrapperStyle = {
		position: "relative",
		w: "100%",
		h: "100%",
		borderRadius: "8px",
		overflow: "hidden",
		cursor: "pointer",
		img: { bgColor: "#393939", transitionDuration: "0.35s" },
		"&:hover": { img: { transform: "scale(1.065)" } },
	};

	const ImgBottomOverLay = (props: { text: string }) => (
		<Box
			position="absolute"
			left="0"
			right="0"
			bottom="0"
			pb="13px"
			bgColor="rgba(0, 0, 0, 0.5)"
			boxShadow="0 -20px 50px 40px rgba(0, 0, 0, 0.5)"
		>
			<Text
				sx={{
					fontSize: "16px",
					fontWeight: "600",
					textAlign: "center",
					lineHeight: "21px",
				}}
			>
				{props.text}
			</Text>
		</Box>
	);

	const TopHeading = () => (
		<Box h="16.4vh" pb="15px" px={{ base: "22px", md: "0" }}>
			<NextLink href="/" passHref>
				<Flex
					as="a"
					justifyContent="flex-end"
					gap="15px"
					fontWeight={500}
					color="darkBg.50"
					mb={{ base: "24px", sm: "32px" }}
					_hover={{ color: "darkBg.50" }}
				>
					חזור אחורה
					<RightArrow />
				</Flex>
			</NextLink>

			<Heading
				sx={{
					fontSize: { base: "34px", sm: "44px", lg: "64px" },
					fontWeight: "600",
					lineHeight: { base: "40px", md: "83px" },
				}}
			>
				Windrop Branding
			</Heading>
		</Box>
	);

	return (
		<>
			<Head>
				<title>Windrop Branding</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box
				as="main"
				pl={{ base: "16px", sm: "60px", lg: "90px" }}
				pr={{ base: "8px", sm: "14px", md: "27px" }}
				pt={{ base: "40px", md: "63px" }}
				h="100vh"
				overflowY="hidden"
			>
				<Box display={{ base: "block", md: "none" }}>
					<TopHeading />
				</Box>

				<Flex gap={{ base: "20px", lg: "30px", xl: "53px" }}>
					<Box display={{ base: "none", md: "block" }} flex={{ base: 0.6, xl: 0.7 }} h="80vh">
						<TopHeading />

						<Box position="relative">
							<Box
								maxH="81vh"
								overflowY="auto"
								borderRadius="8px"
								sx={{ "&::-webkit-scrollbar": { display: "none" } }}
							>
								<img src="/assets/portfolio-item-preview.png" alt="" />
							</Box>

							<Box position="absolute" left="50%" transform="translateX(-50%)" bottom="34px">
								<motion.div
									transition={{ y: { duration: 0.5, yoyo: Infinity, ease: "easeOut" } }}
									animate={{ y: ["-1.5rem", "-2.5rem"] }}
								>
									<Flex
										alignItems="center"
										gap="18px"
										fontWeight={500}
										color="#2E2E2E"
										sx={{ svg: { fill: "#2E2E2E", transform: "rotate(90deg)" } }}
									>
										המשך לגלול
										<RightArrow />
									</Flex>
								</motion.div>
							</Box>
						</Box>
					</Box>

					<Flex
						h="80vh"
						flex={{ base: "1", md: 0.4, xl: 0.3 }}
						flexDir="column"
						gap={{ base: "14px", sm: "33px" }}
						pr={{ base: "10px", sm: "20px", md: "29px" }}
						mt={{ md: "16.4vh" }}
						overflowY="auto"
						sx={{
							"&::-webkit-scrollbar": {
								w: "13px",
							},
							"&::-webkit-scrollbar-thumb": {
								borderRadius: "8px",
								bgColor: "primary",
							},
							"&::-webkit-scrollbar-track": {
								borderRadius: "10px",
								bgColor: "darkBg.200",
							},
						}}
					>
						<Box sx={{ ...ImgWrapperStyle, minH: "415px" }}>
							<Image src="/assets/gallery-item-1.png" alt="" layout="fill" />
							<ImgBottomOverLay text="מיתוג" />
						</Box>

						<Flex minH="240px" gap={{ base: "15px", sm: "35px" }}>
							<Box sx={ImgWrapperStyle}>
								<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
								<ImgBottomOverLay text="מיתוג" />
							</Box>
							<Box sx={ImgWrapperStyle}>
								<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
								<ImgBottomOverLay text="מיתוג" />
							</Box>
						</Flex>

						<Box sx={{ ...ImgWrapperStyle, minH: "415px" }}>
							<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
							<ImgBottomOverLay text="מיתוג" />
						</Box>

						<Flex minH="240px" gap={{ base: "15px", sm: "35px" }}>
							<Box sx={ImgWrapperStyle}>
								<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
								<ImgBottomOverLay text="מיתוג" />
							</Box>
							<Box sx={ImgWrapperStyle}>
								<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
								<ImgBottomOverLay text="מיתוג" />
							</Box>
						</Flex>

						<Box sx={{ ...ImgWrapperStyle, minH: "415px" }}>
							<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
							<ImgBottomOverLay text="מיתוג" />
						</Box>

						<Flex minH="240px" gap={{ base: "15px", sm: "35px" }}>
							<Box sx={ImgWrapperStyle}>
								<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
								<ImgBottomOverLay text="מיתוג" />
							</Box>
							<Box sx={ImgWrapperStyle}>
								<Image src="/assets/gallery-item-*.png" alt="" layout="fill" />
								<ImgBottomOverLay text="מיתוג" />
							</Box>
						</Flex>
					</Flex>
				</Flex>
			</Box>
		</>
	);
};

export default Branding;
